apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - volume.yaml
  - vs.yaml
namePrefix: memos-
images:
  - name: ghcr.io/guyzsarun-lab/base
    newName: neosmemo/memos
    newTag: "0.25"
commonLabels:
  app: memos
patches:
  - path: patches/deployment.yaml
  - path: patches/service.yaml
