apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- vs.yaml
- secret.yaml
namePrefix: apple-health-exporter-
images:
- name: ghcr.io/guyzsarun-lab/base
  newName: ghcr.io/guyzsarun/apple-health-influxdb
  newTag: v0.0.1
commonLabels:
  app: apple-health-exporter
patches:
- path: patches/deployment.yaml
- path: patches/service.yaml


